version: "3.6"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: launchpad.web
    environment:
      APP_ENV: dev
      DJANGO_SUPERUSER_PASSWORD: admin
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
    volumes:
      - './launchpad/:/launchpad/'
      - '~/.kube/config:/.kube/config:ro'
      - '${HOME}/.minikube/:${HOME}/.minikube/:ro'
    ports:
      - "8080:8000"
    command: /bin/sh -c "sh scripts/entrypoint.sh python manage.py runserver 0.0.0.0:8000"
    networks:
      - postgres_net
      - redis_net
      - minikube

  db:
    image: postgres:12
    restart: unless-stopped
    container_name: launchpad.db
    ports:
      - 5432
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: launchpad_db
    networks:
      - postgres_net

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: dev
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
    command: /bin/sh -c "sh scripts/worker.sh"
    container_name: launchpad.celery
    volumes:
      - './launchpad/:/launchpad/'
      - '~/.kube/config:/.kube/config:ro'
      - '${HOME}/.minikube/:${HOME}/.minikube/:ro'
    networks:
      - redis_net
      - postgres_net
      - minikube

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: dev
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
    command: /bin/sh -c "sh scripts/beat.sh"
    container_name: launchpad.beat
    volumes:
      - './launchpad/:/launchpad/'
      - '~/.kube/config:/.kube/config:ro'
      - '${HOME}/.minikube/:${HOME}/.minikube/:ro'
    networks:
      - redis_net
      - postgres_net
      - minikube

  redis:
    image: redis:6
    container_name: launchpad.redis
    ports:
      - "6388:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - redis_net

networks:
  postgres_net:
  redis_net:
  minikube:
    external: true
    name: minikube
