# Generated by Django 3.2.11 on 2022-01-09 18:22

import catalog
import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(default=core.models.default_expiry)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('vscode', 'vscode')], default=catalog.App['VSCODE'], max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='core.session')),
            ],
        ),
    ]
